name: Same Workflow

on:
  pull_request:
    types: [opened, reopened]

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Start Message
        run: echo "Workflow started..."
      - name: Print Start Message-sleep 30
        run: sleep 20
      - name: Print Start Message
        run: echo "Workflow started..."
        
  second-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Start Message
        run: echo "Workflow started..."
      - name: Print Start Message-sleep 30
        run: sleep 30
      - name: Print Start Message
        run: echo "Workflow started..."
